#!/bin/bash
# Device libraries for Emulator 1.5+
# These are located in/system/lib
libs="libicuuc.so librs_jni.so libbluetooth.so libomx_avcdec_sharedlibrary.so libttssynthproxy.so libOMX.TI.AAC.decode.so libicui18n.so libril_rds.so libbluedroid.so libomx_amrenc_sharedlibrary.so libttspico.so libLCML.so libicudata.so libril.so libbinder.so libomx_amrdec_sharedlibrary.so libthread_db.so libIMGegl.so libhardware_legacy.so libreference-ril.so libbattd.so libomx_aacdec_sharedlibrary.so libterm.so libHPImgApi.so libhardware.so libreference-cdma-sms.so libaudiopolicy.so liboemcamera.so libsysutils.so libGLESv2.so libglslcompiler.so libpvrANDROID_WSEGL.so libaudioflinger.so libnmea.so libsystem_server.so libGLESv1_CM.so libexpat.so libpvr2d.so zxing.so libaudio.so libnetutils.so libsurfaceflinger_client.so libFLAC.so libexif.so libpppd_plugin-ril.so libandroid_servers.so libnetlink.so libsurfaceflinger.so libFFTEm.so libemoji.so libpixelflinger.so libandroid_runtime.so libncurses.so libstlport.so libETC1.so libdvm.so libpagemap.so libacc.so libnativehelper.so libstdc++.so libEGL.so libdrm1_jni.so libopencorehw.so liba2dp.so libmoto_ril.so libstagefrighthw.so invoke_mock_media_player.so libdrm1.so libopencore_rtspreg.so libvoicesearch.so libVendor_ti_omx_config_parser.so libmoto_gps.so libstagefright_omx.so libdl.so libopencore_rtsp.so libimageutils.so libVendor_ti_omx.so libmediaplayerservice.so libstagefright_color_conversion.so libdiskconfig.so libopencore_player.so libSR_AudioIn.so libmedia_jni.so libstagefright_avc_common.so libdbus.so libopencore_net_support.so libRS.so libmedia.so libstagefright_amrnb_common.so libcutils.so libopencore_mp4localreg.so libOMX_Core.so libm.so libstagefright.so libctest.so libopencore_mp4local.so libOMX.TI.WMA.decode.so liblzo.so libssl.so libcrypto.so libopencore_downloadreg.so libzxing.so libOMX.TI.WBAMR.encode.so liblvmxipc.so libsrv_um.so hw/sensors.sholes.so hw/sensors.goldfish.so hw/overlay.omap3.so hw/lights.sholes.so hw/gralloc.omap3.so hw/gralloc.default.so libcameraservice.so libopencore_download.so libz.so libOMX.TI.WBAMR.decode.so liblog.so libsrec_jni.so libcamera_client.so libopencore_common.so libxml2wbxml.so libOMX.TI.Video.encoder.so libjpeg.so libsqlite.so libcamera.so libopencore_author.so libwpa_client.so libOMX.TI.Video.Decoder.so libjnigraphics.so libspeech.so libc_malloc_debug_qemu.so libopencore_asflocalreg.so bluez-plugin/input.so bluez-plugin/audio.so libwebcore.so libOMX.TI.MP3.decode.so libjni_pinyinime.so libsoundpool.so libc_malloc_debug_leak.so libopencore_asflocal.so libwbxml_jni.so libOMX.TI.JPEG.Encoder.so libjni_latinime.so libsonivox.so libc.so libomx_sharedlibrary.so libvorbisidec.so libOMX.TI.AMR.encode.so libiprouteutil.so libskiagl.so egl/libGLESv2_POWERVR_SGX530_121.so egl/libGLESv1_CM_POWERVR_SGX530_121.so egl/libGLES_android.so egl/libEGL_POWERVR_SGX530_121.so libbridge.so libomx_mp3dec_sharedlibrary.so libutils.so libOMX.TI.AMR.decode.so libinterstitial.so libskia.so libbluetoothd.so libomx_m4vdec_sharedlibrary.so libui.so libOMX.TI.AAC.encode.so"

# Loop thru lib names
for lib in $libs
do
# Pull the library into the local file system
adb pull /system/lib/$lib ./
done

